name: Build Badges

on: [push]

jobs:
  answer-badge:
    name: Create Answer Badge
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: "Run test coverage"
        run: |
          python -m pytest --cov=src src
      - name: "Create json report"
        run: |
          python -m coverage json --omit='*/tests/*'
      - name: "Extract coverage value"
        run: |
          python -c "import json; print(json.load(open('coverage.json', 'rb'))['totals']['percent_covered'])"
      - name: "Clean up temporary directory"
        run: |
          rm coverage.json .coverage