name: Build Badges

on: [push]

jobs:
  answer-badge:
    name: Create Answer Badge
    runs-on: ubuntu-latest
    steps:
      - name: Create the Badge
        uses: loic.diridollou/gh-action
        with:
          TEST: answer.json
          