name: CI/CD Pipeline for Bike Service Monitor
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  ci_job:
    name: Linting and testing
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: "Linting"
        run: |
          pylint src
      - name: "Testing"
        run: |
          pytest src
  deployment_job:
    name: Deploying to Heroku
    runs-on: ubuntu-latest
    steps:
      if: success()
      run: echo "success"