name: CI/CD Pipeline for Bike Service Monitor
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build_and_deploy:
    name: Linting, testing and deploying
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: "Linting"
        run: |
          pylint src; pylint application
      - name: "Testing"
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          pytest src
      - name: Code coverage
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          coverage run -m --source application,src pytest src application;
          coverage json --omit="**/tests/*"
          VARIABLE=$(python -c "import json; print(round(json.load(open('coverage.json', 'rb'))['totals']['percent_covered'], 2))")
          echo "::set-output name=changelog::$VARIABLE"
        id: step1
      - name: print coverage
        run: |
          coverage report -m
      - name: Create Awesome Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 1bfc8baf02ee8afb083b1feb4063082c
          filename: coverage.json
          label: Code coverage
          message: ${{ steps.step1.outputs.changelog }}
          color: yellowgreen
      - name: print codecov
        run: |
          echo 