name: Email sender
on:
  schedule:
    - cron: '8 16 * * *'

jobs:
  my_first_job:
    name: Emailing
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: "Emailing"
        run: |
          python clock.py